import type { ExportPayload } from "../../domain/types";
import { SCHEMA_VERSION } from "../../domain/types";

export function buildSamplePayload(): ExportPayload {
  const pid = "sample-profile";
  const now = new Date().toISOString();
  const pastDay = (days: number) => {
    const d = new Date();
    d.setDate(d.getDate() - days);
    return d.toISOString();
  };
  const futureDay = (days: number) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    return d.toISOString();
  };

  const skill = (id: string, name: string, current: number, target = 4) => ({
    id,
    profileId: pid,
    name,
    currentLevel: current,
    targetLevel: target,
    weight: 1,
    assessedAt: pastDay(7),
  });

  const p1 = "phase-pm-1";
  const p2 = "phase-pm-2";
  const p3 = "phase-pm-3";
  const p4 = "phase-pm-4";
  const p5 = "phase-pm-5";

  const ms1 = "ms-pm-101";
  const ms2 = "ms-pm-102";
  const ms3 = "ms-pm-201";
  const ms4 = "ms-pm-202";
  const ms5 = "ms-pm-301";
  const ms6 = "ms-pm-401";
  const ms7 = "ms-pm-501";

  return {
    schemaVersion: SCHEMA_VERSION,
    exportedAt: now,
    profile: {
      id: pid,
      createdAt: pastDay(30),
      updatedAt: now,
      timezone: "America/New_York",
      targetRole: "Associate Product Manager",
      rolePresetId: "product_manager",
      educationLevel: "undergrad_y3",
      targetDate: futureDay(120).slice(0, 10),
      weeklyAvailableHours: 14,
      onboardingCompletedAt: pastDay(30),
      isSampleProfile: true,
    },
    skills: [
      skill("s1", "Product Thinking", 3, 5),
      skill("s2", "User Research", 4, 4),
      skill("s3", "Communication", 3, 5),
      skill("s4", "Analytics & Metrics", 2, 4),
      skill("s5", "SQL & Data Extraction", 2, 3),
      skill("s6", "Leadership & Cross-functional", 3, 4),
      skill("s7", "Problem Solving & Case Studies", 3, 5),
    ],
    phases: [
      {
        id: p1,
        profileId: pid,
        title: "PM Foundations & Mental Models",
        description: "Master first-principles product thinking, strategy frameworks, and user discovery fundamentals.",
        order: 0,
        startDate: pastDay(30).slice(0, 10),
        endDate: pastDay(15).slice(0, 10),
      },
      {
        id: p2,
        profileId: pid,
        title: "Product Discovery & User Research",
        description: "Formulate customer hypotheses, conduct structured interviews, and synthesize qualitative insights.",
        order: 1,
        startDate: pastDay(14).slice(0, 10),
        endDate: futureDay(10).slice(0, 10),
      },
      {
        id: p3,
        profileId: pid,
        title: "Product Analytics & Growth Metrics",
        description: "Define North Star metrics, map out conversion funnels, and practice SQL-driven cohort retention analysis.",
        order: 2,
        startDate: futureDay(11).slice(0, 10),
        endDate: futureDay(40).slice(0, 10),
      },
      {
        id: p4,
        profileId: pid,
        title: "Execution, Specs & Portfolio Evidence",
        description: "Author complete PRDs, prioritize feature backlogs with RICE, and publish teardown case studies.",
        order: 3,
        startDate: futureDay(41).slice(0, 10),
        endDate: futureDay(80).slice(0, 10),
      },
      {
        id: p5,
        profileId: pid,
        title: "Internship Readiness & Case Interviews",
        description: "Practice product design mock interviews, analytical estimation questions, and application outreach.",
        order: 4,
        startDate: futureDay(81).slice(0, 10),
        endDate: futureDay(120).slice(0, 10),
      },
    ],
    milestones: [
      {
        id: ms1,
        profileId: pid,
        phaseId: p1,
        title: "Deconstruct Core PM Mental Models",
        relatedSkillIds: ["s1", "s3"],
        order: 0,
        targetDate: pastDay(20).slice(0, 10),
        status: "completed",
        isCustom: false,
        createdAt: pastDay(30),
        updatedAt: pastDay(20),
      },
      {
        id: ms2,
        profileId: pid,
        phaseId: p1,
        title: "Conduct an In-Depth Product Teardown",
        relatedSkillIds: ["s1", "s7"],
        order: 1,
        targetDate: pastDay(15).slice(0, 10),
        status: "completed",
        isCustom: false,
        createdAt: pastDay(30),
        updatedAt: pastDay(15),
      },
      {
        id: ms3,
        profileId: pid,
        phaseId: p2,
        title: "Execute 5 User Discovery Interviews",
        relatedSkillIds: ["s2", "s3"],
        order: 0,
        targetDate: futureDay(2).slice(0, 10),
        status: "in_progress",
        isCustom: false,
        createdAt: pastDay(14),
        updatedAt: pastDay(2),
      },
      {
        id: ms4,
        profileId: pid,
        phaseId: p2,
        title: "Synthesize Customer Journey & Pain Matrix",
        relatedSkillIds: ["s2", "s7"],
        order: 1,
        targetDate: futureDay(10).slice(0, 10),
        status: "not_started",
        isCustom: false,
        createdAt: pastDay(14),
        updatedAt: pastDay(14),
      },
      {
        id: ms5,
        profileId: pid,
        phaseId: p3,
        title: "Define North Star & Product Funnel Metrics",
        relatedSkillIds: ["s4", "s5"],
        order: 0,
        targetDate: futureDay(25).slice(0, 10),
        status: "not_started",
        isCustom: false,
        createdAt: pastDay(14),
        updatedAt: pastDay(14),
      },
      {
        id: ms6,
        profileId: pid,
        phaseId: p4,
        title: "Author a Full Production PRD & Roadmap",
        relatedSkillIds: ["s1", "s3", "s6"],
        order: 0,
        targetDate: futureDay(60).slice(0, 10),
        status: "not_started",
        isCustom: false,
        createdAt: pastDay(14),
        updatedAt: pastDay(14),
      },
      {
        id: ms7,
        profileId: pid,
        phaseId: p5,
        title: "Complete 10 APM Mock Case Interviews",
        relatedSkillIds: ["s7", "s3"],
        order: 0,
        targetDate: futureDay(100).slice(0, 10),
        status: "not_started",
        isCustom: false,
        createdAt: pastDay(14),
        updatedAt: pastDay(14),
      },
    ],
    roadmapTasks: [
      {
        id: "t1",
        profileId: pid,
        milestoneId: ms3,
        title: "Prepare structured interview script for student onboarding",
        order: 0,
        priority: "High",
        dueAt: futureDay(1),
        status: "in_progress",
        createdAt: pastDay(5),
        updatedAt: pastDay(1),
      },
      {
        id: "t2",
        profileId: pid,
        milestoneId: ms3,
        title: "Record and transcribe 3 target user discovery calls",
        order: 1,
        priority: "High",
        dueAt: futureDay(3),
        status: "pending",
        createdAt: pastDay(5),
        updatedAt: pastDay(5),
      },
      {
        id: "t3",
        profileId: pid,
        milestoneId: ms3,
        title: "Extract top 3 recurring friction points into insight backlog",
        order: 2,
        priority: "Medium",
        dueAt: futureDay(5),
        status: "pending",
        createdAt: pastDay(5),
        updatedAt: pastDay(5),
      },
      {
        id: "t4",
        profileId: pid,
        milestoneId: ms1,
        title: "Read 'Inspired' Chapters 1-8 by Marty Cagan",
        order: 0,
        priority: "Medium",
        dueAt: pastDay(22),
        status: "completed",
        completedAt: pastDay(22),
        createdAt: pastDay(30),
        updatedAt: pastDay(22),
      },
      {
        id: "t5",
        profileId: pid,
        milestoneId: ms2,
        title: "Publish Linear vs Notion teardown doc with screenshots",
        order: 0,
        priority: "High",
        dueAt: pastDay(15),
        status: "completed",
        completedAt: pastDay(15),
        createdAt: pastDay(25),
        updatedAt: pastDay(15),
      },
    ],
    focusSessions: [
      {
        id: "f1",
        profileId: pid,
        roadmapTaskId: "t4",
        startedAt: pastDay(4),
        endedAt: pastDay(4),
        durationSeconds: 1500,
        plannedSeconds: 1500,
        status: "completed",
        completedAt: pastDay(4),
      },
      {
        id: "f2",
        profileId: pid,
        roadmapTaskId: "t5",
        startedAt: pastDay(3),
        endedAt: pastDay(3),
        durationSeconds: 1500,
        plannedSeconds: 1500,
        status: "completed",
        completedAt: pastDay(3),
      },
      {
        id: "f3",
        profileId: pid,
        roadmapTaskId: "t1",
        startedAt: pastDay(2),
        endedAt: pastDay(2),
        durationSeconds: 1500,
        plannedSeconds: 1500,
        status: "completed",
        completedAt: pastDay(2),
      },
      {
        id: "f4",
        profileId: pid,
        roadmapTaskId: "t1",
        startedAt: pastDay(1),
        endedAt: pastDay(1),
        durationSeconds: 1500,
        plannedSeconds: 1500,
        status: "completed",
        completedAt: pastDay(1),
      },
      {
        id: "f5",
        profileId: pid,
        roadmapTaskId: "t1",
        startedAt: now,
        endedAt: now,
        durationSeconds: 1500,
        plannedSeconds: 1500,
        status: "completed",
        completedAt: now,
      },
    ],
    opportunities: [
      {
        id: "opp-1",
        profileId: pid,
        company: "Monzo Bank",
        role: "Associate Product Manager Intern (Summer 2026)",
        status: "Interview",
        location: "London, UK (Hybrid)",
        jobDescription: "Join the Monzo Business Experience team to streamline merchant onboarding and transaction categorization.",
        notes: "Second round product sense interview scheduled for next Tuesday with Head of Product.",
        savedAt: pastDay(20),
        appliedAt: pastDay(14),
        createdAt: pastDay(20),
        updatedAt: pastDay(2),
      },
      {
        id: "opp-2",
        profileId: pid,
        company: "Spotify",
        role: "Product Management Intern - Creator Tools",
        status: "Assessment",
        location: "Stockholm / Remote",
        jobDescription: "Help indie musicians publish and track their live audience engagement metrics in Spotify for Artists.",
        savedAt: pastDay(15),
        appliedAt: pastDay(7),
        createdAt: pastDay(15),
        updatedAt: pastDay(3),
      },
      {
        id: "opp-3",
        profileId: pid,
        company: "Canva",
        role: "Product Growth Intern",
        status: "Applied",
        location: "Sydney / Remote",
        jobDescription: "Optimize student collaboration features and team sharing invitations.",
        savedAt: pastDay(10),
        appliedAt: pastDay(4),
        createdAt: pastDay(10),
        updatedAt: pastDay(4),
      },
      {
        id: "opp-4",
        profileId: pid,
        company: "Deliveroo",
        role: "Product Operations & Strategy Intern",
        status: "Saved",
        location: "London, UK",
        jobDescription: "Analyze rider dispatch times and restaurant fulfillment efficiency.",
        savedAt: pastDay(2),
        createdAt: pastDay(2),
        updatedAt: pastDay(2),
      },
    ],
    opportunityStatusEvents: [
      { id: "ev1", opportunityId: "opp-1", toStatus: "Saved", changedAt: pastDay(20) },
      { id: "ev2", opportunityId: "opp-1", toStatus: "Applied", changedAt: pastDay(14) },
      { id: "ev3", opportunityId: "opp-1", toStatus: "Interview", changedAt: pastDay(2) },
      { id: "ev4", opportunityId: "opp-2", toStatus: "Applied", changedAt: pastDay(7) },
      { id: "ev5", opportunityId: "opp-2", toStatus: "Assessment", changedAt: pastDay(3) },
      { id: "ev6", opportunityId: "opp-3", toStatus: "Applied", changedAt: pastDay(4) },
      { id: "ev7", opportunityId: "opp-4", toStatus: "Saved", changedAt: pastDay(2) },
    ],
    notes: [
      {
        id: "n1",
        profileId: pid,
        title: "Monzo Business Onboarding Teardown Notes",
        body: "# Monzo Merchant Funnel\n\n1. Verification step takes 4 minutes on average.\n2. Key friction: manual business registration number entry.\n3. Opportunity: auto-fill from UK Companies House API.\n\n### Metric Impact\n- Projected 14% drop in onboarding drop-offs.",
        linkedEntityType: "opportunity",
        linkedEntityId: "opp-1",
        createdAt: pastDay(6),
        updatedAt: pastDay(2),
      },
      {
        id: "n2",
        profileId: pid,
        title: "A/B Testing Framework Summary",
        body: "Hypothesis: By adding 1-click social login, registration conversion will increase by 8% with 95% statistical significance over a 14-day sample.",
        linkedEntityType: "milestone",
        linkedEntityId: ms2,
        createdAt: pastDay(12),
        updatedAt: pastDay(12),
      },
    ],
    whiteboards: [],
    personalTodos: [
      {
        id: "todo1",
        profileId: pid,
        title: "Update LinkedIn headline to 'Aspiring APM | Building APTIMI'",
        priority: "High",
        status: "pending",
        dueAt: futureDay(2),
        createdAt: pastDay(3),
        updatedAt: pastDay(3),
      },
      {
        id: "todo2",
        profileId: pid,
        title: "Schedule 20-min coffee chat with alumni PM at Spotify",
        priority: "Medium",
        status: "pending",
        dueAt: futureDay(4),
        createdAt: pastDay(2),
        updatedAt: pastDay(2),
      },
    ],
    reminders: [],
    inAppNotifications: [
      {
        id: "notif1",
        profileId: pid,
        type: "milestone",
        title: "Milestone Completed!",
        body: "You deconstructed Core PM Mental Models and earned 50 career XP.",
        scheduledAt: pastDay(15),
        createdAt: pastDay(15),
        state: "read",
      },
      {
        id: "notif2",
        profileId: pid,
        type: "reminder",
        title: "Interview Prep Reminder",
        body: "Monzo PM Interview in 3 days. Review your product teardown notes!",
        scheduledAt: now,
        createdAt: now,
        state: "unread",
      },
    ],
    rewardLedger: [
      {
        id: "rw1",
        profileId: pid,
        sourceType: "milestoneComplete",
        sourceId: ms1,
        points: 50,
        idempotencyKey: "msComplete:ms-pm-101",
        reason: "Completed Milestone: Deconstruct Core PM Mental Models",
        awardedAt: pastDay(20),
      },
      {
        id: "rw2",
        profileId: pid,
        sourceType: "milestoneComplete",
        sourceId: ms2,
        points: 50,
        idempotencyKey: "msComplete:ms-pm-102",
        reason: "Completed Milestone: Conduct an In-Depth Product Teardown",
        awardedAt: pastDay(15),
      },
      {
        id: "rw3",
        profileId: pid,
        sourceType: "focusSession",
        sourceId: "f1",
        points: 10,
        idempotencyKey: "focus:f1",
        reason: "Completed 25-min focus block",
        awardedAt: pastDay(4),
      },
    ],
    settings: {
      id: "app",
      schemaVersion: SCHEMA_VERSION,
      theme: "system",
      notificationPreference: "in_app_only",
      timezone: "America/New_York",
      aiKeyPersistOptIn: false,
    },
    aiUsage: [],
  };
}
